/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    services: Service;
    media: Media;
    'contact-submissions': ContactSubmission;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('vi' | 'en') | ('vi' | 'en')[];
  globals: {
    'business-info': BusinessInfo;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'business-info': BusinessInfoSelect<false> | BusinessInfoSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'vi' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Pages are built from blocks. Save as draft while you work — nothing is public until you press Publish. The address cannot be changed once a page is published.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Shown as the page heading, and used to suggest the address below.
   */
  title: string;
  /**
   * Add and reorder blocks to build the page.
   */
  layout?:
    | (
        | {
            /**
             * Two or three words in small capitals above the heading. Leave empty to show none.
             */
            eyebrow?: string | null;
            /**
             * The page’s main heading. It becomes the only <h1> on the page, so make it the one thing the page is about.
             */
            heading: string;
            /**
             * One or two sentences under the heading.
             */
            subheading?: string | null;
            /**
             * Shown beside the heading. This is the largest image on the page, so it is loaded first — pick a sharp one.
             */
            image: number | Media;
            /**
             * Two or three words each — the reassurances a visitor scans before clicking. Leave empty to show none.
             */
            highlights?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            secondaryCtaLabel?: string | null;
            /**
             * The quieter action beside the main one. Leave both empty for a single button.
             */
            secondaryCtaHref?: string | null;
            ctaLabel?: string | null;
            /**
             * A path on this site, starting with /. Leave both boxes empty for no button.
             */
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Two or three words in small capitals above the heading. Leave empty to show none.
             */
            eyebrow?: string | null;
            /**
             * A short paragraph shown to the right of the heading on wide screens, and under it on a phone.
             */
            note?: string | null;
            heading?: string | null;
            /**
             * Shown in this order and numbered automatically. Drag to reorder.
             */
            steps?:
              | {
                  title: string;
                  body?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'steps';
          }
        | {
            /**
             * Two or three words in small capitals above the heading. Leave empty to show none.
             */
            eyebrow?: string | null;
            /**
             * A short paragraph shown to the right of the heading on wide screens, and under it on a phone.
             */
            note?: string | null;
            heading?: string | null;
            /**
             * Pick the packages to show, in the order you want them. Prices and durations come from the service itself, so they are never out of date here. Only published services can be chosen.
             */
            services: (number | Service)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            /**
             * Two or three words in small capitals above the heading. Leave empty to show none.
             */
            eyebrow?: string | null;
            /**
             * A short paragraph shown to the right of the heading on wide screens, and under it on a phone.
             */
            note?: string | null;
            /**
             * Shown above the questions. It is page copy — Google’s FAQ data has no place for it.
             */
            heading?: string | null;
            /**
             * These are sent to Google as structured data, so write a real question and a real answer. A row with either half empty is skipped.
             */
            items?:
              | {
                  question: string;
                  /**
                   * Plain text. Formatting is deliberately not available here, because Google reads this answer as text.
                   */
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            /**
             * Two or three words in small capitals above the heading. Leave empty to show none.
             */
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            /**
             * The section heading. It renders as a second-level heading, so it does not compete with the page’s own title.
             */
            heading: string;
            /**
             * One short paragraph under the heading. The phone number, address and opening hours are not written here — they are taken from Business information, so they stay identical to your Google Business Profile.
             */
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
        | {
            richText: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * The image shown when someone shares this page. Left blank, the default from Site settings is used. The 1200×630 version is generated on upload.
     */
    image?: (number | null) | Media;
    /**
     * Normally leave this blank — the system fills in this page’s own address. Only set it when the same content already lives at another URL and you want Google to credit that one instead.
     */
    canonical?: string | null;
    /**
     * The page still works normally, it just will not appear in search results. The system turns this on by itself for a translation that has no SEO title or description of its own yet.
     */
    noindex?: boolean | null;
    /**
     * Never sent to Google and has no effect on ranking. Its only job is to stop two editors writing two different pages against the same term.
     */
    keywordFocus?: string | null;
  };
  /**
   * The part of the URL after the domain, for example "bang-gia". Left blank, it is generated automatically. Each language has its own address. Once published this cannot be changed, because the old URL is already indexed.
   */
  slug: string;
  localeUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Upload images at least 1200px wide. Smaller ones still work, but the Facebook/Zalo share image will be enlarged and slightly soft.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Briefly describe what the image shows. Screen readers read this aloud and Google uses it to understand the image. For example: "A white sedan being washed automatically at AutoWash247". Required.
   */
  alt: string;
  /**
   * Caption shown beneath the image on the page. Leave blank if not needed.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * One entry per wash package. Each becomes its own page, and its price and duration are also sent to Google as structured data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * What customers call this package. Used as the page heading.
   */
  name: string;
  /**
   * Enter the amount in VND as plain digits, for example 150000. No dots, spaces or ₫ — the page adds those when it displays it.
   */
  price: number;
  /**
   * All prices are in Vietnamese dong.
   */
  currency: 'VND';
  /**
   * Roughly how long the wash takes, in minutes. Whole numbers.
   */
  durationMinutes: number;
  /**
   * One line per thing the package covers. Drag to reorder — they are shown in this order.
   */
  includes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * A photo of this wash. Used at the top of the service page and as the share image. Not localized — one photo for both languages.
   */
  image: number | Media;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * The image shown when someone shares this page. Left blank, the default from Site settings is used. The 1200×630 version is generated on upload.
     */
    image?: (number | null) | Media;
    /**
     * Normally leave this blank — the system fills in this page’s own address. Only set it when the same content already lives at another URL and you want Google to credit that one instead.
     */
    canonical?: string | null;
    /**
     * The page still works normally, it just will not appear in search results. The system turns this on by itself for a translation that has no SEO title or description of its own yet.
     */
    noindex?: boolean | null;
    /**
     * Never sent to Google and has no effect on ranking. Its only job is to stop two editors writing two different pages against the same term.
     */
    keywordFocus?: string | null;
  };
  /**
   * The part of the URL after the domain, for example "rua-xe-nhanh". Left blank, it is generated automatically. Each language has its own address. Once published this cannot be changed, because the old URL is already indexed.
   */
  slug: string;
  localeUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Messages sent through the contact form, newest first. They are read-only: this is a record of what someone sent, so nothing here can be edited.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  /**
   * As the visitor typed it. Call back on this number.
   */
  phone: string;
  email?: string | null;
  /**
   * What the visitor said they were after, in their own words — not a link to a service, so it still makes sense after a package is renamed.
   */
  service?: string | null;
  message: string;
  /**
   * Which version of the site this was sent from. Reply in that language.
   */
  locale: 'vi' | 'en';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Administrator: full access, including deleting and managing users. Editor: add and edit content, cannot delete.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              image?: T;
              highlights?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        steps?:
          | T
          | {
              eyebrow?: T;
              note?: T;
              heading?: T;
              steps?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              eyebrow?: T;
              note?: T;
              heading?: T;
              services?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              eyebrow?: T;
              note?: T;
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              richText?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noindex?: T;
        keywordFocus?: T;
      };
  slug?: T;
  localeUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  price?: T;
  currency?: T;
  durationMinutes?: T;
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  image?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noindex?: T;
        keywordFocus?: T;
      };
  slug?: T;
  localeUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  service?: T;
  message?: T;
  locale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Name, address, phone and opening hours. These appear in the footer, on the contact page, and in the structured data Google reads. They must match your Google Business Profile exactly, character for character.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-info".
 */
export interface BusinessInfo {
  id: number;
  /**
   * Exactly as registered and as it appears on Google Business Profile.
   */
  legalName: string;
  /**
   * House number and street only. The district goes in the next field.
   */
  streetAddress: string;
  locality: string;
  postalCode?: string | null;
  /**
   * From Google Maps: right-click your location on the map and click the coordinates to copy them. Latitude is the first number.
   */
  lat?: number | null;
  /**
   * The second of the two numbers copied from Google Maps.
   */
  lng?: number | null;
  /**
   * Write it the way a customer would dial it. Keep it identical to Google Business Profile, spacing included.
   */
  phone: string;
  /**
   * Optional. A phone number, or a zalo.me link.
   */
  zalo?: string | null;
  /**
   * One row per weekday, already in order. Tick "Closed" for a day you do not open; its times then disappear. Use 24-hour times.
   */
  openingHours?:
    | {
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        closed?: boolean | null;
        opens?: string | null;
        closes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * A rough range, shown in search results. Not a price list — the services carry their own prices.
   */
  priceRange?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Brand, default SEO values and social links used across the whole site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * The trading name, as customers know it. Used in page titles. This is the short name — the registered legal name lives in Business information.
   */
  brandName: string;
  /**
   * The small icon shown in the browser tab. A square image works best.
   */
  favicon?: (number | null) | Media;
  /**
   * Shown in the footer. Leave empty for any platform you do not use.
   */
  socialLinks?:
    | {
        platform: 'facebook' | 'zalo' | 'youtube' | 'tiktok' | 'instagram';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Appended to every page title, including the separator. Google truncates titles near 60 characters, so keep it short.
   */
  titleSuffix?: string | null;
  /**
   * One or two sentences describing the business, used when a page has no description of its own. Around 150 characters reads best in search results; 180 is the maximum.
   */
  defaultDescription?: string | null;
  /**
   * Shown when a page has no share image of its own. Facebook and Zalo crop to 1200x630, which the upload generates for you.
   */
  ogFallback?: (number | null) | Media;
  /**
   * From Google Analytics: Admin → Data streams → your stream. Starts with "G-". Leave blank to load no analytics at all.
   */
  ga4MeasurementId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-info_select".
 */
export interface BusinessInfoSelect<T extends boolean = true> {
  legalName?: T;
  streetAddress?: T;
  locality?: T;
  postalCode?: T;
  lat?: T;
  lng?: T;
  phone?: T;
  zalo?: T;
  openingHours?:
    | T
    | {
        day?: T;
        closed?: T;
        opens?: T;
        closes?: T;
        id?: T;
      };
  priceRange?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  favicon?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  titleSuffix?: T;
  defaultDescription?: T;
  ogFallback?: T;
  ga4MeasurementId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}